use std::io;
use std::os::fd::AsRawFd;
use std::os::fd::RawFd;

use epoll::{ControlOptions, Event, Events};

use crate::channel_manager::*;
use crate::polled_fd::*;

// There are at most 5 targets: child in/out/err, server sock, client sock
// epoll groups results by file descriptor so we won't get multiple events
// on the same target in one invocation
const POLLSTER_MAX_FDS: usize = 5;

/// Wraps a [`ChannelManager`] and invokes its methods when epoll reports events
/// on file descriptors that the channel manager provided via [`PolledFdSet`].
pub struct Pollster<Manager: ChannelManager> {
    poll_fd: i32,
    close_fd: RawFd,
    events: [Event; POLLSTER_MAX_FDS],
    fd_set: PolledFdSet,
    channel_mgr: Manager,
}

impl<Manager: ChannelManager> Pollster<Manager> {
    /// Creates a pollster that operates on the provided [`ChannelManager`]. The
    /// file descriptor is for close notifications; when it becomes readable,
    /// the pollster breaks out of its [`run`] function.
    pub fn new<C: AsRawFd>(mut channel_mgr: Manager, close_notify: &C) -> io::Result<Self> {
        epoll::create(true).and_then(|fd| {
            let close_fd = close_notify.as_raw_fd();
            let close_event = epoll::Event::new(epoll::Events::EPOLLIN, close_fd as u64);
            epoll::ctl(fd, ControlOptions::EPOLL_CTL_ADD, close_fd, close_event)?;

            let mut fd_set = PolledFdSet::new();
            channel_mgr.initialize(&mut fd_set);
            let mut p = Pollster {
                poll_fd: fd,
                close_fd,
                events: [Event::new(Events::empty(), 0); _],
                channel_mgr,
                fd_set,
            };
            p.apply_poll_updates()?;
            Ok(p)
        })
    }

    /// Processes all poll modification requests generated by the channel manager.
    fn apply_poll_updates(&mut self) -> io::Result<()> {
        self.fd_set.apply_updates(
            |fd, events| {
                let event = epoll::Event::new(events, fd as u64);
                epoll::ctl(
                    self.poll_fd,
                    ControlOptions::EPOLL_CTL_ADD,
                    fd,
                    event.clone(),
                )?;
                Ok(PolledFd::new(fd, event))
            },
            |fd, event| epoll::ctl(self.poll_fd, ControlOptions::EPOLL_CTL_MOD, fd, event),
            |fd| {
                let dummy = epoll::Event::new(epoll::Events::empty(), fd as u64);
                epoll::ctl(self.poll_fd, ControlOptions::EPOLL_CTL_DEL, fd, dummy)
            },
        )
    }

    /// The pollster main loop. Waits for IO events and dispatches them to the
    /// channel manager. Exits when a fatal error occurs or the close file
    /// descriptor becomes readable.
    pub fn run(mut self) -> io::Result<()> {
        loop {
            let num_events = match epoll::wait(self.poll_fd, -1, &mut self.events) {
                Ok(n) => n,
                Err(err) if err.kind() == io::ErrorKind::Interrupted => 0,
                Err(err) => return Err(err),
            };

            // Avoids race conditions in the tests, where epoll decides to
            // reports a specific event at the same time as the close
            // notification but in a different order.
            let mut final_iteration = false;

            for i in 0..num_events {
                let event = &self.events[i];
                let fd = event.data as RawFd;
                if fd == self.close_fd {
                    final_iteration = true;
                    continue;
                }

                let actions = epoll::Events::from_bits_truncate(event.events);
                if actions.contains(epoll::Events::EPOLLIN) {
                    self.channel_mgr.on_readable(fd, &mut self.fd_set)?;
                }
                if actions.contains(epoll::Events::EPOLLOUT) {
                    self.channel_mgr.on_writable(fd, &mut self.fd_set)?;
                }
                if actions.contains(epoll::Events::EPOLLERR)
                    || actions.contains(epoll::Events::EPOLLHUP)
                {
                    self.channel_mgr.on_hangup(fd, &mut self.fd_set)?;
                }
            }

            if final_iteration {
                return Ok(());
            } else if num_events > 0 {
                self.apply_poll_updates()?;
            }
        }
    }
}

#[cfg(test)]
mod test {
    use std::io::{pipe, ErrorKind, PipeWriter, Read, Write};
    use std::net::Shutdown;
    use std::os::unix::net::{UnixListener, UnixStream};
    use std::path::PathBuf;
    use std::sync::mpsc::{sync_channel, Receiver, SyncSender};
    use std::thread::JoinHandle;
    use std::{env, fs, thread};

    use super::*;

    #[derive(PartialEq, Debug)]
    enum ChannelManagerReq {
        Initialize,
        OnReadable(RawFd),
        OnWritable(RawFd),
        OnHangup(RawFd),
        Drop,
    }

    enum ChannelManagerResp {
        PollReadable(RawFd, bool),
        PollWritable(RawFd, bool),
        Register(RawFd, epoll::Events),
        Unregister(RawFd),
        IoError(io::ErrorKind),
    }

    /// An adapter between the callback-based [`ChannelManager`] trait and a
    /// synchronous helper function that runs on a separate thread. Each
    /// callback in the blocking channel manager sends a request and waits for
    /// the response before returning.
    struct BlockingChannelManager {
        req_send: SyncSender<ChannelManagerReq>,
        resp_recv: Receiver<Vec<ChannelManagerResp>>,
    }

    impl BlockingChannelManager {
        fn new() -> (
            Self,
            Receiver<ChannelManagerReq>,
            SyncSender<Vec<ChannelManagerResp>>,
        ) {
            let (req_send, req_recv) = sync_channel(0);
            let (resp_send, resp_recv) = sync_channel(0);
            (
                BlockingChannelManager {
                    req_send,
                    resp_recv,
                },
                req_recv,
                resp_send,
            )
        }

        fn process_resp(
            &mut self,
            resp: Vec<ChannelManagerResp>,
            fd_set: &mut PolledFdSet,
        ) -> io::Result<()> {
            use ChannelManagerResp::*;

            let mut result = Ok(());
            for r in resp {
                match r {
                    PollReadable(fd, enable) => fd_set.modify(&fd, |pfd| pfd.poll_for_read(enable)),
                    PollWritable(fd, enable) => {
                        fd_set.modify(&fd, |pfd| pfd.poll_for_write(enable))
                    }
                    Register(fd, events) => fd_set.register(&fd, events),
                    Unregister(fd) => fd_set.unregister(&fd),
                    IoError(error_kind) => result = Err(error_kind.into()),
                }
            }
            result
        }
    }

    impl ChannelManager for BlockingChannelManager {
        fn initialize(&mut self, fd_set: &mut PolledFdSet) {
            // We can't panic here even if the the other side of the channels
            // does. It may do asserts so panicking is expected, but we should
            // avoid it since this is run in a forked subprocess which may do
            // strange things to the test runner's state if it returns to it.
            if let Ok(_) = self.req_send.send(ChannelManagerReq::Initialize) {
                self.process_resp(self.resp_recv.recv().unwrap(), fd_set)
                    .unwrap()
            }
        }

        fn on_readable(&mut self, fd: RawFd, fd_set: &mut PolledFdSet) -> io::Result<()> {
            if let Ok(_) = self.req_send.send(ChannelManagerReq::OnReadable(fd)) {
                self.process_resp(self.resp_recv.recv().unwrap(), fd_set)
            } else {
                Ok(())
            }
        }

        fn on_writable(&mut self, fd: RawFd, fd_set: &mut PolledFdSet) -> io::Result<()> {
            if let Ok(_) = self.req_send.send(ChannelManagerReq::OnWritable(fd)) {
                self.process_resp(self.resp_recv.recv().unwrap(), fd_set)
            } else {
                Ok(())
            }
        }

        fn on_hangup(&mut self, fd: RawFd, fd_set: &mut PolledFdSet) -> io::Result<()> {
            if let Ok(_) = self.req_send.send(ChannelManagerReq::OnHangup(fd)) {
                self.process_resp(self.resp_recv.recv().unwrap(), fd_set)
            } else {
                Ok(())
            }
        }
    }

    impl Drop for BlockingChannelManager {
        fn drop(&mut self) {
            self.req_send.send(ChannelManagerReq::Drop).unwrap();
            self.resp_recv.recv().unwrap();
        }
    }

    /// Writes a byte to the provided pipe and flushes it. Used in a
    /// [`run_channel_test`] worker function to stop the pollster at the end of
    /// a test.
    fn write_close_byte(mut close_write: PipeWriter) -> io::Result<()> {
        close_write.write(&[1u8]).and_then(|_| close_write.flush())
    }

    /// Writes all the events received on the channel to stderr. This should
    /// only be used for debugging, since it has no exit condition and will run
    /// until the test process is killed.
    #[allow(unused)]
    fn dump_pending_events(
        req_recv: &Receiver<ChannelManagerReq>,
        resp_send: &SyncSender<Vec<ChannelManagerResp>>,
    ) {
        loop {
            let event = req_recv.recv().unwrap();
            eprintln!("Received event: {event:?}");
            resp_send.send(Vec::new()).unwrap();
        }
    }

    /// Executes a test defined by a worker function. The worker is provided
    /// with a pipe and two channels linked to a [`BlockingChannelManager`].
    /// It uses the channels to monitor [`Pollster`] events and request changes
    /// in monitored file descriptors. The pollster drives this interaction:
    /// receiving on the request channel will block until a pollster event
    /// occurs, then the worker must send a change list on the response channel.
    /// Failing to do so will deadlock the pollster. Writing on the pipe causes
    /// the pollster to exit and generate a [`ChannelManagerReq::Drop`] event
    /// (this event must still reply with a response list for synchronization,
    /// though it will typically be empty)
    ///
    /// Internally this function runs the test inside a secondary thread of a
    /// child process. The child process is used to allow easy termination if
    /// the test fails to complete on time. The secondary thread lets the main
    /// thread of the child process run the pollster until the worker writes to
    /// the close pipe.
    fn run_channel_test<F>(test: F)
    where
        F: FnOnce(PipeWriter, Receiver<ChannelManagerReq>, SyncSender<Vec<ChannelManagerResp>>)
            + Send
            + 'static,
    {
        let (close_read, close_write) = pipe().unwrap();
        let (channel_manager, req_recv, resp_send) = BlockingChannelManager::new();
        let helper = thread::spawn(move || {
            test(close_write, req_recv, resp_send);
        });

        let pollster = Pollster::new(channel_manager, &close_read).unwrap();
        pollster.run().unwrap();

        helper.join().unwrap();
    }

    #[test]
    fn can_stop_via_channel() {
        run_channel_test(|close_write, req_recv, resp_send| {
            use ChannelManagerReq::*;

            assert_eq!(Initialize, req_recv.recv().unwrap());
            resp_send.send(Vec::new()).unwrap();

            // Ensure that this actually generates a Drop event and exits the
            // child process
            write_close_byte(close_write).unwrap();

            assert_eq!(Drop, req_recv.recv().unwrap());
            resp_send.send(Vec::new()).unwrap();
        });
    }

    #[test]
    fn pipe_readable_and_hangup() {
        run_channel_test(|close_write, req_recv, resp_send| {
            use ChannelManagerReq::*;
            use ChannelManagerResp::*;

            let (mut msg_read, mut msg_write) = pipe().unwrap();
            let msg_read_fd = msg_read.as_raw_fd();
            assert_eq!(Initialize, req_recv.recv().unwrap());
            resp_send
                .send(vec![Register(msg_read_fd, epoll::Events::EPOLLIN)])
                .unwrap();

            assert_eq!(1, msg_write.write(&[42u8]).unwrap());
            msg_write.flush().unwrap();

            assert_eq!(OnReadable(msg_read_fd), req_recv.recv().unwrap());
            let mut buffer = [0u8; 1];
            assert_eq!(1, msg_read.read(&mut buffer).unwrap());
            assert_eq!(42, buffer[0]);
            resp_send.send(Vec::new()).unwrap();

            // After this point we should get a hangup, since the file
            // descriptor can no longer do anything. This is different from a
            // socket where shutdown only occurs on the write end because a read
            // may still be possible.
            drop(msg_write);

            assert_eq!(OnHangup(msg_read_fd), req_recv.recv().unwrap());
            resp_send.send(Vec::new()).unwrap();

            write_close_byte(close_write).unwrap();

            // We might get additional hangups here since those are reported
            // immediately, while the pipe write will take time to propagate.
            loop {
                match req_recv.recv().unwrap() {
                    OnHangup(fd) => {
                        assert_eq!(fd, msg_read_fd);
                        resp_send.send(Vec::new()).unwrap();
                    }
                    Drop => {
                        resp_send.send(Vec::new()).unwrap();
                        break;
                    }
                    event => panic!("Unexpected event: {event:?}"),
                }
            }
        });
    }

    #[test]
    fn pipe_readable_unregister() {
        run_channel_test(|close_write, req_recv, resp_send| {
            use ChannelManagerReq::*;
            use ChannelManagerResp::*;

            let (mut msg_read, mut msg_write) = pipe().unwrap();
            let msg_read_fd = msg_read.as_raw_fd();
            assert_eq!(Initialize, req_recv.recv().unwrap());
            resp_send
                .send(vec![Register(msg_read_fd, epoll::Events::EPOLLIN)])
                .unwrap();

            assert_eq!(1, msg_write.write(&[42u8]).unwrap());
            msg_write.flush().unwrap();

            assert_eq!(OnReadable(msg_read_fd), req_recv.recv().unwrap());
            let mut buffer = [0u8; 1];
            assert_eq!(1, msg_read.read(&mut buffer).unwrap());
            assert_eq!(42, buffer[0]);
            resp_send.send(vec![Unregister(msg_read_fd)]).unwrap();

            // Unregistering here should bypass the hangup we would normally
            // get. Since there is no hangup event after we close msg_write, we
            // have to send the close byte immediately.

            drop(msg_write);
            write_close_byte(close_write).unwrap();

            assert_eq!(Drop, req_recv.recv().unwrap());
            resp_send.send(Vec::new()).unwrap();
        });
    }

    #[test]
    fn pipe_readable_partial_read() {
        run_channel_test(|close_write, req_recv, resp_send| {
            use ChannelManagerReq::*;
            use ChannelManagerResp::*;

            let (mut msg_read, mut msg_write) = pipe().unwrap();
            let msg_read_fd = msg_read.as_raw_fd();
            assert_eq!(Initialize, req_recv.recv().unwrap());
            resp_send
                .send(vec![Register(msg_read_fd, epoll::Events::EPOLLIN)])
                .unwrap();

            assert_eq!(2, msg_write.write(&[42u8, 43u8]).unwrap());
            msg_write.flush().unwrap();

            assert_eq!(OnReadable(msg_read_fd), req_recv.recv().unwrap());
            let mut buffer = [0u8; 1];
            assert_eq!(1, msg_read.read(&mut buffer).unwrap());
            assert_eq!(42, buffer[0]);
            resp_send.send(Vec::new()).unwrap();

            drop(msg_write);

            // We're testing two things here:
            //
            // - Pollster operates in level-triggered mode. The data in the
            //   buffer should trigger an additional event, not be ignored as in
            //   edge-triggered mode.
            //
            // - If there's unread data in the buffer, we should be notified
            //   about that data before the hangup. Internally these may happen
            //   in the same epoll wait but the pollster has to enforce this
            //   order. Otherwise we may close the file descriptor to soon.
            assert_eq!(OnReadable(msg_read_fd), req_recv.recv().unwrap());
            let mut buffer = [0u8; 1];
            assert_eq!(1, msg_read.read(&mut buffer).unwrap());
            assert_eq!(43, buffer[0]);
            resp_send.send(Vec::new()).unwrap();

            assert_eq!(OnHangup(msg_read_fd), req_recv.recv().unwrap());
            resp_send.send(vec![Unregister(msg_read_fd)]).unwrap();

            write_close_byte(close_write).unwrap();

            assert_eq!(Drop, req_recv.recv().unwrap());
            resp_send.send(Vec::new()).unwrap();
        });
    }

    #[test]
    fn pipe_writable() {
        run_channel_test(|close_write, req_recv, resp_send| {
            use ChannelManagerReq::*;
            use ChannelManagerResp::*;

            let (mut msg_read, mut msg_write) = pipe().unwrap();
            let msg_write_fd = msg_write.as_raw_fd();
            assert_eq!(Initialize, req_recv.recv().unwrap());
            resp_send
                .send(vec![Register(msg_write_fd, epoll::Events::EPOLLOUT)])
                .unwrap();

            assert_eq!(2, msg_write.write(&[42u8, 43u8]).unwrap());
            msg_write.flush().unwrap();

            assert_eq!(OnWritable(msg_write_fd), req_recv.recv().unwrap());
            assert_eq!(1, msg_write.write(&[42u8]).unwrap());
            msg_write.flush().unwrap();
            resp_send.send(Vec::new()).unwrap();

            let mut buffer = [0u8; 1];
            assert_eq!(1, msg_read.read(&mut buffer).unwrap());
            assert_eq!(42, buffer[0]);

            // This should happen without us having to do anything. The file
            // descriptor should report that it's writable as long as the file
            // descriptor is alive and the pipe's buffer has space.
            assert_eq!(OnWritable(msg_write_fd), req_recv.recv().unwrap());
            resp_send
                .send(vec![PollWritable(msg_write_fd, false)])
                .unwrap();

            drop(msg_read);

            assert_eq!(OnHangup(msg_write_fd), req_recv.recv().unwrap());
            resp_send.send(Vec::new()).unwrap();

            write_close_byte(close_write).unwrap();

            // We might get additional hangups here since those are reported
            // immediately, while the pipe write will take time to propagate.
            loop {
                match req_recv.recv().unwrap() {
                    OnHangup(fd) => {
                        assert_eq!(fd, msg_write_fd);
                        resp_send.send(Vec::new()).unwrap();
                    }
                    Drop => {
                        resp_send.send(Vec::new()).unwrap();
                        break;
                    }
                    event => panic!("Unexpected event: {event:?}"),
                }
            }
        });
    }

    #[test]
    fn pipe_writable_no_hangup() {
        run_channel_test(|close_write, req_recv, resp_send| {
            use ChannelManagerReq::*;
            use ChannelManagerResp::*;

            let (mut msg_read, mut msg_write) = pipe().unwrap();
            let msg_write_fd = msg_write.as_raw_fd();
            assert_eq!(Initialize, req_recv.recv().unwrap());
            resp_send
                .send(vec![Register(msg_write_fd, epoll::Events::EPOLLOUT)])
                .unwrap();

            assert_eq!(2, msg_write.write(&[42u8, 43u8]).unwrap());
            msg_write.flush().unwrap();

            assert_eq!(OnWritable(msg_write_fd), req_recv.recv().unwrap());
            assert_eq!(1, msg_write.write(&[42u8]).unwrap());
            msg_write.flush().unwrap();
            resp_send.send(vec![Unregister(msg_write_fd)]).unwrap();

            let mut buffer = [0u8; 1];
            assert_eq!(1, msg_read.read(&mut buffer).unwrap());
            assert_eq!(42, buffer[0]);

            // Unregistering should suppress the hangup we would normally get.
            // Since there is no intervening event, we have to both close the
            // reader and send the close notify

            drop(msg_read);
            write_close_byte(close_write).unwrap();

            assert_eq!(Drop, req_recv.recv().unwrap());
            resp_send.send(Vec::new()).unwrap();
        });
    }

    fn run_socket_test<F>(test: F)
    where
        F: FnOnce(
                PipeWriter,
                Receiver<ChannelManagerReq>,
                SyncSender<Vec<ChannelManagerResp>>,
                UnixListener,
                JoinHandle<UnixStream>,
            ) + Send
            + 'static,
    {
        let temp_dir = PathBuf::new().join(env::temp_dir()).join("iosock");
        if !temp_dir.is_dir() {
            fs::create_dir(&temp_dir).unwrap();
        }

        let socket_path = temp_dir.join("socket");
        match fs::remove_file(&socket_path) {
            Ok(()) => (),
            Err(err) if err.kind() == ErrorKind::NotFound => (),
            Err(_) => panic!("Could not remove stale socket"),
        }

        run_channel_test(move |close_write, req_recv, resp_send| {
            let listener = UnixListener::bind(&socket_path).unwrap();
            let worker = thread::spawn(move || UnixStream::connect(socket_path).unwrap());
            test(close_write, req_recv, resp_send, listener, worker)
        });
    }

    #[test]
    fn socket_accept_recv_send() {
        run_socket_test(|close_write, req_recv, resp_send, listener, peer_worker| {
            use ChannelManagerReq::*;
            use ChannelManagerResp::*;

            assert_eq!(Initialize, req_recv.recv().unwrap());
            let listen_fd = listener.as_raw_fd();
            resp_send
                .send(vec![Register(listen_fd, epoll::Events::EPOLLIN)])
                .unwrap();

            assert_eq!(OnReadable(listen_fd), req_recv.recv().unwrap());
            let (mut client, _) = listener.accept().unwrap();
            let client_fd = client.as_raw_fd();
            resp_send
                .send(vec![Register(client_fd, epoll::Events::EPOLLIN)])
                .unwrap();

            let mut peer = peer_worker.join().unwrap();
            assert_eq!(1, peer.write(&[42u8]).unwrap());
            peer.flush().unwrap();

            assert_eq!(OnReadable(client_fd), req_recv.recv().unwrap());
            let mut buffer = [0u8];
            assert_eq!(1, client.read(&mut buffer).unwrap());
            assert_eq!(42, buffer[0]);
            resp_send.send(vec![PollWritable(client_fd, true)]).unwrap();

            assert_eq!(OnWritable(client_fd), req_recv.recv().unwrap());
            assert_eq!(1, client.write(&[43u8]).unwrap());
            client.flush().unwrap();
            resp_send
                .send(vec![PollWritable(client_fd, false)])
                .unwrap();

            assert_eq!(1, peer.read(&mut buffer).unwrap());
            assert_eq!(43, buffer[0]);

            drop(peer);

            assert_eq!(OnReadable(client_fd), req_recv.recv().unwrap());
            assert_eq!(0, client.read(&mut buffer).unwrap());
            resp_send.send(vec![Unregister(client_fd)]).unwrap();

            // This event occurring after the Unregister is not a bug. It is
            // effectively an assertion that epoll detected both the read and
            // write hangup at the same time. If they happened separately then a
            // second epoll call would have happened after the Unregister.
            assert_eq!(OnHangup(client_fd), req_recv.recv().unwrap());
            resp_send.send(Vec::new()).unwrap();

            write_close_byte(close_write).unwrap();

            assert_eq!(Drop, req_recv.recv().unwrap());
            resp_send.send(Vec::new()).unwrap();
        });
    }

    #[test]
    fn socket_read_shutdown() {
        run_socket_test(|close_write, req_recv, resp_send, listener, peer_worker| {
            use ChannelManagerReq::*;
            use ChannelManagerResp::*;

            assert_eq!(Initialize, req_recv.recv().unwrap());
            let listen_fd = listener.as_raw_fd();
            resp_send
                .send(vec![Register(listen_fd, epoll::Events::EPOLLIN)])
                .unwrap();

            assert_eq!(OnReadable(listen_fd), req_recv.recv().unwrap());
            let (mut client, _) = listener.accept().unwrap();
            let client_fd = client.as_raw_fd();
            let mut client_events = epoll::Events::EPOLLIN;
            client_events.set(epoll::Events::EPOLLOUT, true);
            resp_send
                .send(vec![Register(client_fd, client_events)])
                .unwrap();

            // We'll only get write notifications right now, if we act on them
            // we'll get EPIPE which should be treated the same as a hangup.
            let mut peer = peer_worker.join().unwrap();
            peer.shutdown(Shutdown::Read).unwrap();

            assert_eq!(OnWritable(client_fd), req_recv.recv().unwrap());
            resp_send.send(Vec::new()).unwrap();

            assert_eq!(
                ErrorKind::BrokenPipe,
                client
                    .write(&[42u8])
                    .and_then(|_| client.flush())
                    .expect_err("Expected BrokenPipe error when writing to shutdown socket")
                    .kind()
            );

            assert_eq!(1, peer.write(&[42u8]).unwrap());
            peer.flush().unwrap();

            // We'll get more writable notifications until this read propagates.
            let mut buffer = [0u8];
            loop {
                match req_recv.recv().unwrap() {
                    OnWritable(fd) => {
                        assert_eq!(fd, client_fd);
                        resp_send.send(Vec::new()).unwrap();
                    }
                    OnReadable(fd) => {
                        assert_eq!(fd, client_fd);
                        assert_eq!(1, client.read(&mut buffer).unwrap());
                        assert_eq!(42, buffer[0]);
                        resp_send.send(Vec::new()).unwrap();
                        break;
                    }
                    event => panic!("Unexpected event: {event:?}"),
                }
            }

            drop(peer);

            // At this point the socket should be readable, writable, and
            // hung-up. Make sure we see each event at least once before we shut
            // it down.

            let mut seen_readable = false;
            let mut seen_writable = false;
            let mut seen_hup = false;
            while !(seen_readable && seen_writable && seen_hup) {
                let event = req_recv.recv().unwrap();
                match event {
                    OnReadable(fd) => {
                        assert_eq!(fd, client_fd);
                        resp_send.send(vec![]).unwrap();

                        seen_readable = true;
                        assert_eq!(0, client.read(&mut buffer).unwrap());
                    }
                    OnWritable(fd) => {
                        assert_eq!(fd, client_fd);
                        resp_send.send(Vec::new()).unwrap();

                        seen_writable = true;
                        assert_eq!(
                            ErrorKind::BrokenPipe,
                            client
                                .write(&[42u8])
                                .and_then(|_| client.flush())
                                .expect_err(
                                    "Expected BrokenPipe error when writing to shutdown socket"
                                )
                                .kind()
                        );
                    }
                    OnHangup(fd) => {
                        assert_eq!(fd, client_fd);
                        resp_send.send(Vec::new()).unwrap();
                        seen_hup = true;
                    }
                    event => panic!("Unexpected event: {event:?}"),
                }
            }

            write_close_byte(close_write).unwrap();

            loop {
                let event = req_recv.recv().unwrap();
                match event {
                    OnReadable(fd) => {
                        assert_eq!(fd, client_fd);
                        resp_send.send(vec![]).unwrap();

                        assert_eq!(0, client.read(&mut buffer).unwrap());
                    }
                    OnWritable(fd) => {
                        assert_eq!(fd, client_fd);
                        resp_send.send(Vec::new()).unwrap();

                        assert_eq!(
                            ErrorKind::BrokenPipe,
                            client
                                .write(&[42u8])
                                .and_then(|_| client.flush())
                                .expect_err(
                                    "Expected BrokenPipe error when writing to shutdown socket"
                                )
                                .kind()
                        );
                    }
                    OnHangup(fd) => {
                        assert_eq!(fd, client_fd);
                        resp_send.send(Vec::new()).unwrap();
                    }
                    Drop => {
                        resp_send.send(Vec::new()).unwrap();
                        break;
                    }
                    event => panic!("Unexpected event: {event:?}"),
                }
            }
        });
    }

    #[test]
    fn socket_write_shutdown() {
        run_socket_test(|close_write, req_recv, resp_send, listener, peer_worker| {
            use ChannelManagerReq::*;
            use ChannelManagerResp::*;

            assert_eq!(Initialize, req_recv.recv().unwrap());
            let listen_fd = listener.as_raw_fd();
            resp_send
                .send(vec![Register(listen_fd, epoll::Events::EPOLLIN)])
                .unwrap();

            assert_eq!(OnReadable(listen_fd), req_recv.recv().unwrap());
            let (mut client, _) = listener.accept().unwrap();
            let client_fd = client.as_raw_fd();
            resp_send
                .send(vec![Register(client_fd, epoll::Events::EPOLLIN)])
                .unwrap();

            let peer = peer_worker.join().unwrap();
            peer.shutdown(Shutdown::Write).unwrap();

            let mut buffer = [0u8];
            assert_eq!(OnReadable(client_fd), req_recv.recv().unwrap());
            resp_send.send(vec![]).unwrap();
            assert_eq!(0, client.read(&mut buffer).unwrap());

            drop(peer);

            // At this point the socket should be readable and hung-up. Make
            // sure we see each event at least once before we shut it down.

            let mut seen_readable = false;
            let mut seen_hup = false;
            while !(seen_readable && seen_hup) {
                let event = req_recv.recv().unwrap();
                match event {
                    OnReadable(fd) => {
                        assert_eq!(fd, client_fd);
                        resp_send.send(vec![]).unwrap();

                        seen_readable = true;
                        assert_eq!(0, client.read(&mut buffer).unwrap());
                    }
                    OnHangup(fd) => {
                        assert_eq!(fd, client_fd);
                        resp_send.send(Vec::new()).unwrap();
                        seen_hup = true;
                    }
                    event => panic!("Unexpected event: {event:?}"),
                }
            }

            write_close_byte(close_write).unwrap();

            loop {
                let event = req_recv.recv().unwrap();
                match event {
                    OnReadable(fd) => {
                        assert_eq!(fd, client_fd);
                        resp_send.send(vec![]).unwrap();

                        assert_eq!(0, client.read(&mut buffer).unwrap());
                    }
                    OnHangup(fd) => {
                        assert_eq!(fd, client_fd);
                        resp_send.send(Vec::new()).unwrap();
                    }
                    Drop => {
                        resp_send.send(Vec::new()).unwrap();
                        break;
                    }
                    event => panic!("Unexpected event: {event:?}"),
                }
            }
        });
    }
}
